keymappings:
  hotbar:
    - mouse4
    - q
    - e
    - r
    - mouse5
    - "6"
    - "7"
    - "8"
    - "9"
  inventory: f
  drop: g
  sneak: shift

sort_hotbar:
  Diamond Sword: 0
  Iron Sword: 0
  Stone Sword: 0
  Wooden Sword: 0
  Pickaxe: 1
  Shears: 2
  Axe: 3
  Wool: 4

window:
  INV_X1: 0.33203125
  INV_X9: 0.670703125
  INV_Y: 0.7809027777

network:
  port: 1234

mouse:
  sensitivity_pitch: 0.15
  sensitivity_yaw: 0.15

ninjabridge:  # From facing positive X, right positive Z to this
  direction:
    - -0.183021702095792971
    - -0.9659224156856066
    - -0.183021702095792971
  position:  # away from the center of the original block
    - 0.79531914661104
    - 0.2819803207912

godbridge:  # From facing positive X, right positive Z to this
  direction:
    - -0.166875561273452635920
    - -0.9717536180016725
    - -0.166875561273452635920
  position:  # away from the center of the original block
    - 0.79531914661104
    - 0.2819803207912
